version: '3.8'

services:
  frontend:
    build: ./Flights-Booking-Frontend-React
    ports:
      - '80:80'
    depends_on:
      - backend

  backend:
    build: ./Flights-Booking-Backend-Node.js
    ports:
      - '3000:3000'
    environment:
      - PORT_HOST=3000
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=asd
      - DATABASE_DATABASE_NAME=postgres
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asd
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: