name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run backend tests
      run: npm test

    - name: Build frontend
      run: npm run build

    - name: Install Render CLI
      run: curl -fsSL https://render.com/static/cli/install.sh | bash

    - name: Authenticate Render CLI
      env:
        RENDER_API_KEY: rnd_n7XCEOATjWXAYubIYXUzdshy8CWB
      run: render login --api-key $RENDER_API_KEY

    - name: Deploy Backend to Render
      run: render deploy service srv-ct3mcmlumphs73dvkfb0

    - name: Deploy Frontend to Render
      run: render deploy service srv-ct3vd2m8ii6s73d9o9lg